<?php
function get_predefined_acls(&$modules) {
    $modules = array(
        '/sample' => array('name' => 'sample', 'icon' => 'bars', 'public' => true),
        '/sample/dashboard' => array('name' => 'dashboard', 'icon' => 'dashboard', 'public' => true),
        '/sample/exception' => array('name' => 'exception', 'icon' => 'warning', 'public' => true),
        '/sample/form' => array('name' => 'form', 'icon' => 'form', 'public' => true),
        '/sample/list' => array('name' => 'list', 'icon' => 'table', 'public' => true),
        '/sample/list/search' => array('name' => 'search', 'icon' => '', 'public' => true),
        '/sample/profile' => array('name' => 'profile', 'icon' => 'profile', 'public' => true),
        '/sample/result' => array('name' => 'result', 'icon' => 'check-circle-o', 'public' => true),
        '/system' => array('name' => 'system', 'icon' => '', 'public' => true),
        '/system/settings' => array('name' => 'settings', 'icon' => 'setting', 'public' => true),
        '/system/user' => array('name' => 'user', 'icon' => '', 'public' => true),
        '/portal' => array('name' => 'portal', 'icon' => 'undefined', 'page' => false, 'public' => true),
        '/sample/dashboard/workplace' => array('name' => 'workplace', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/dashboard/monitor' => array('name' => 'monitor', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/exception/403' => array('name' => '403', 'icon' => 'exception', 'page' => false, 'public' => true),
        '/sample/exception/404' => array('name' => '404', 'icon' => 'question-circle-o', 'page' => false, 'public' => true),
        '/sample/exception/500' => array('name' => '500', 'icon' => 'close-circle-o', 'page' => false, 'public' => true),
        '/sample/form/basic-form' => array('name' => 'basic-form', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/form/step-form' => array('name' => 'step-form', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/form/advanced-form' => array('name' => 'advanced-form', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/form/step-form/info' => array('name' => 'info', 'icon' => 'undefined', 'page' => true, 'public' => false),
        '/sample/form/step-form/confirm' => array('name' => 'confirm', 'icon' => 'undefined', 'page' => true, 'public' => false),
        '/sample/form/step-form/result' => array('name' => 'result', 'icon' => 'undefined', 'page' => true, 'public' => false),
        '/sample/list/table' => array('name' => 'table', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/list/basic' => array('name' => 'basic', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/list/card' => array('name' => 'card', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/list/search/applications' => array('name' => 'applications', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/list/search/articles' => array('name' => 'articles', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/list/search/projects' => array('name' => 'projects', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/profile/advanced' => array('name' => 'advanced', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/profile/basic' => array('name' => 'basic', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/profile/books' => array('name' => 'books', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/result/fail' => array('name' => 'fail', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/sample/result/success' => array('name' => 'success', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/system/settings/basic' => array('name' => 'basic', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/system/settings/features' => array('name' => 'features', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/system/user/users' => array('name' => 'users', 'icon' => 'user', 'page' => false, 'public' => false),
        '/system/user/role' => array('name' => 'role', 'icon' => 'undefined', 'page' => false, 'public' => false),
        '/test' => array('name' => 'test', 'icon' => 'file', 'page' => false, 'public' => true),

    );
}
